Fix react-native-web example
1. Add the package `react-dom` that was missing.
2. Update `react` to `16.7.0` to fix this error:
`index.js:28 Uncaught TypeError: (0 , _unstableNativeDependencies.injectEventPluginsByName) is not a function`
3. Update `react-native-web` to `10.0.0`